name: Flutter Web Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # 👈 gives Actions permission to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web release
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build/web
          force_orphan: true  # 👈 ensures a clean gh-pages branch
